// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnkb3HcPt_ebIdFL0nIYaqCDehTDaBlvY',
    appId: '1:151028918126:web:32669453d8992dfc51037f',
    messagingSenderId: '151028918126',
    projectId: 'social-media-adeb4',
    authDomain: 'social-media-adeb4.firebaseapp.com',
    storageBucket: 'social-media-adeb4.appspot.com',
    measurementId: 'G-G4FQREK97F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfLMyQC32SV9ARufsQsJusUMV1VoXLHw0',
    appId: '1:151028918126:android:8de2c3636667827b51037f',
    messagingSenderId: '151028918126',
    projectId: 'social-media-adeb4',
    storageBucket: 'social-media-adeb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHyia8lPDIaAj0ECvrS8FpW74KpeRjGEo',
    appId: '1:151028918126:ios:27a895539964808651037f',
    messagingSenderId: '151028918126',
    projectId: 'social-media-adeb4',
    storageBucket: 'social-media-adeb4.appspot.com',
    iosBundleId: 'com.example.socialmediaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHyia8lPDIaAj0ECvrS8FpW74KpeRjGEo',
    appId: '1:151028918126:ios:bdba53e6563e46a951037f',
    messagingSenderId: '151028918126',
    projectId: 'social-media-adeb4',
    storageBucket: 'social-media-adeb4.appspot.com',
    iosBundleId: 'com.example.socialmediaapp.RunnerTests',
  );
}
